name: Release

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]


permissions:
  contents: write

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build and push radicle-cloud
        id: radicle_cloud
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: gcr.io/radicle-services/radicle-cloud:latest,gcr.io/radicle-services/radicle-cloud:${{ github.sha }},gcr.io/radicle-services/radicle-cloud:${{ github.ref_name }}
          cache-from: type=registry,ref=gcr.io/radicle-services/radicle-cloud:latest
          cache-to: type=inline
